### ISSUE TITLE
can't create a token

### ISSUE THREAD

**Issue by sragatsky** [mcorbin/meuse#21]
version 0.5.0

when following the example in the documentation:
`curl --header "Content-Type: application/json" --request POST --data '{"name":"test_token","validity":10,"user":"root_user","password":"do_not_use_this_password"}' localhost:8855/api/v1/meuse/token
`

the result is
```
java.lang.NoSuchMethodError: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;
	at byte_streams.char_sequence$lazy_char_buffer_sequence$fn__11298.invoke(char_sequence.clj:77)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$seq__5402.invoke(core.clj:137)
	at byte_streams.char_sequence$decode_byte_source$reify__11308.toString(char_sequence.clj:120)
	at byte_streams$fn__11633$f__11337__auto____11634.invoke(byte_streams.clj:556)
	at byte_streams.graph$conversion_fn$fn__10929$fn__10930.invoke(graph.clj:259)
	at clojure.lang.PersistentUnrolledVector$Card2.reduce(PersistentUnrolledVector.java:482)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at byte_streams.graph$conversion_fn$fn__10929.invoke(graph.clj:253)
	at byte_streams$convert.invokeStatic(byte_streams.clj:193)
	at byte_streams$convert.invoke(byte_streams.clj:162)
	at byte_streams$convert.invokeStatic(byte_streams.clj:177)
	at byte_streams$convert.invoke(byte_streams.clj:162)
	at meuse.request$convert_body_edn$fn__12262.invoke(request.clj:14)
	at clojure.core$update.invokeStatic(core.clj:6196)
	at clojure.core$update.invoke(core.clj:6188)
	at meuse.request$convert_body_edn.invokeStatic(request.clj:12)
	at meuse.request$convert_body_edn.invoke(request.clj:7)
	at meuse.interceptor.route$fn__18506.invokeStatic(route.clj:72)
	at meuse.interceptor.route$fn__18506.invoke(route.clj:69)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at meuse.interceptor.route$fn__18518.invokeStatic(route.clj:92)
	at meuse.interceptor.route$fn__18518.invoke(route.clj:87)
	at exoscale.interceptor.impl$invoke_stage.invokeStatic(impl.cljc:45)
	at exoscale.interceptor.impl$invoke_stage.invoke(impl.cljc:39)
	at exoscale.interceptor.impl$enter.invokeStatic(impl.cljc:77)
	at exoscale.interceptor.impl$enter.invoke(impl.cljc:65)
	at exoscale.interceptor.impl$execute.invokeStatic(impl.cljc:104)
	at exoscale.interceptor.impl$execute.invoke(impl.cljc:101)
	at exoscale.interceptor$execute.invokeStatic(interceptor.cljc:41)
	at exoscale.interceptor$execute.invoke(interceptor.cljc:8)
	at exoscale.interceptor$execute.invokeStatic(interceptor.cljc:39)
	at exoscale.interceptor$execute.invoke(interceptor.cljc:8)
	at meuse.http$interceptor_handler$handler__18755.invoke(http.clj:44)
	at aleph.http.server$handle_request$fn__15150$f__8803__auto____15151.invoke(server.clj:166)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__8695$f__8696.invoke(executor.clj:47)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mcorbin** [comment]
Hello,

Which Java version are you using ?

**Comment by sragatsky** [comment]
java -version
```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode
```

**Comment by mcorbin** [comment]
Meuse should run on java 11 at least.

**Comment by sragatsky** [comment]
You are right, i missed that.
once i updated my java version, everything worked!

thank you for the quick support!

**Comment by mcorbin** [comment]
You're welcome ;)
