### ISSUE TITLE
Cargo yank fails with exception

### ISSUE THREAD

**Issue by Victor-N-Suadicani** [mcorbin/meuse#45]
Got an error when trying to run cargo yank. From the logs:

```
java.io.FileNotFoundException: /app/registry/se/rv/mycrate (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at clojure.java.io$fn__11520.invokeStatic(io.clj:229)
	at clojure.java.io$fn__11520.invoke(io.clj:229)
	at clojure.java.io$fn__11433$G__11426__11440.invoke(io.clj:69)
	at clojure.java.io$fn__11532.invokeStatic(io.clj:258)
	at clojure.java.io$fn__11532.invoke(io.clj:254)
	at clojure.java.io$fn__11433$G__11426__11440.invoke(io.clj:69)
	at clojure.java.io$fn__11494.invokeStatic(io.clj:165)
	at clojure.java.io$fn__11494.invoke(io.clj:165)
	at clojure.java.io$fn__11446$G__11422__11453.invoke(io.clj:69)
	at clojure.java.io$reader.invokeStatic(io.clj:102)
	at clojure.java.io$reader.doInvoke(io.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$slurp.invokeStatic(core.clj:6944)
	at clojure.core$slurp.doInvoke(core.clj:6944)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at meuse.metadata$update_yank.invokeStatic(metadata.clj:65)
	at meuse.metadata$update_yank.invoke(metadata.clj:61)
	at meuse.api.crate.yank$update_yank$fn__12902.invoke(yank.clj:26)
	at meuse.api.crate.yank$update_yank.invokeStatic(yank.clj:25)
	at meuse.api.crate.yank$update_yank.invoke(yank.clj:11)
	at meuse.api.crate.yank$yank.invokeStatic(yank.clj:41)
	at meuse.api.crate.yank$yank.invoke(yank.clj:39)
	at meuse.inject$inject_crate_api_BANG_$fn__17980.invoke(inject.clj:115)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at meuse.interceptor.route$fn__18970.invokeStatic(route.clj:66)
	at meuse.interceptor.route$fn__18970.invoke(route.clj:56)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at meuse.interceptor.route$fn__18996.invokeStatic(route.clj:107)
	at meuse.interceptor.route$fn__18996.invoke(route.clj:102)
	at exoscale.interceptor.impl$invoke_stage.invokeStatic(impl.cljc:45)
	at exoscale.interceptor.impl$invoke_stage.invoke(impl.cljc:39)
	at exoscale.interceptor.impl$enter.invokeStatic(impl.cljc:77)
	at exoscale.interceptor.impl$enter.invoke(impl.cljc:65)
	at exoscale.interceptor.impl$execute.invokeStatic(impl.cljc:104)
	at exoscale.interceptor.impl$execute.invoke(impl.cljc:101)
	at exoscale.interceptor$execute.invokeStatic(interceptor.cljc:41)
	at exoscale.interceptor$execute.invoke(interceptor.cljc:8)
	at exoscale.interceptor$execute.invokeStatic(interceptor.cljc:39)
	at exoscale.interceptor$execute.invoke(interceptor.cljc:8)
	at meuse.http$interceptor_handler$handler__19386.invoke(http.clj:43)
	at ring.adapter.jetty$proxy_handler$fn__19341.invoke(jetty.clj:27)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mcorbin** [comment]
Hello,

Are you trying to yank a non-existing crate ?

**Comment by Victor-N-Suadicani** [comment]
No - however, I did try to reset the git repository of the registry and I think this caused some of the issues.
